@extends('errors.minimal')
@section('code', '403')
@section('icon', 'shield-x')
@section('message', 'You do not have access')
@section('detail', 'Your account is not allowed on this page. Ask an administrator to grant you access under User Management.')
